import Header from "@/components/shared/header";
import { auth } from "@/lib/auth";
import { SessionType } from "@/lib/types";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = (await auth()) as unknown as SessionType;

  return (
    <>
      <Header session={session} />
      <main>{children}</main>
    </>
  );
}
